# -*- coding: utf-8 -*-
"""cleanerp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PRytn7qCAQCgvpxJT1MfA1DIqJn1NLor
"""

import pandas as pd
import itertools as it

df = pd.read_csv("erpbitsgoa_mycourses.csv", index_col = 0)
df = df.drop(columns = ['Session', 'FN/AN', 'Room'])
df['Subject'] = df['Subject'].str.replace(" +", " ", regex = True)
df_ = df.drop_duplicates(keep = 'first')
df_

df.equals(df_)



edf = df[['Subject', 'Exam Date']]
edf = edf.drop_duplicates(subset = 'Subject', keep = 'first').reset_index().drop('index', axis = 1)
edf

xdf = edf.copy()
xdf = xdf.set_index('Exam Date')
xdf = xdf.groupby(level = 0, axis = 0).agg(list)
i = it.count(1)
for row in xdf.iterrows():
  print(row[0])
  for sub in row[1][0]:
    print(f"{next(i)}. {sub}")
  print('\n')

type_df = df[['Subject', 'Type']].drop_duplicates(keep = 'first').reset_index().drop('index', axis = 1)
hels_df = type_df[type_df['Type'] == 'HEL']
hels_df
for i,s in enumerate(hels_df['Subject'], start = 1):
  print(f"{i}. {s}", end = "\r\n")

for sub in df['Subject'].drop_duplicates(keep = 'first'):
  print(f"'{sub}': '',", end = '\n')

short_sub = {
'BITS F225 - ENVIRONMENTAL STUDIES': 'EVS',
'MATH F211 - MATHEMATICS III': 'M3',
'PHY F211 - CLASSICAL MECHANICS': 'CM',
'PHY F212 - ELECTROMAGNETIC THEO I': 'EMT1',
'PHY F213 - OPTICS': 'Optics',
'PHY F214 - ELEC MAGNET & OPTICS LAB': 'EMOlab',
'HSS F236 - SYMBOLIC LOGIC': 'symb log',
'HSS F343 - PROFESSIONAL ETHICS': 'ethics',
'HSS F235 - INTRODUCTORY PHILOSOPHY': 'phil',
'GS F211 - MOD POLITICAL CONCEPTS': 'MPC',
'HSS F222 - LINGUISTICS': 'ling',
'HSS F374 - Urban Modernity and the Renewal of Paris': 'paris',
'HSS F373 - Shakespeare and Popular Culture': 'shakesp',
'HSS F371 - Cities-Life Issues and Conflicts': 'cities life',
'HSS F363 - DISASTER AND DEVELOPMENT': 'DAD',
'HSS F337 - English Literary Form and Movement': 'ELFM',
'HSS F233 - MAIN TRENDS IN IND HIST': 'ind hist',
'HSS F227 - CROSS CULTURAL SKILLS': 'CCS',
'HSS F346 - INTERNATIONAL RELATIONS': 'int rel',
'HSS F347 - INTRO TO CARNATIC MUSIC': 'carnatic',
'GS F212 - ENVIRON DEV & CLIMATE CH': 'climate ch',
'GS F332 - CONTEMPORARY INDIA': 'comtemp ind',
'GS F322 - CRITI ANAL OF LIT & CINE': 'CALC',
'GS F245 - EFFECTIVE PUBLIC SPEAK': 'EPS',
'GS F233 - PUBLIC POLICY': 'pub policy',
'GS F231 - DYN OF SOCIAL CHANGE': 'DOSC',
'GS F234 - DEVELOPMENT ECONOMICS': 'dev eco',
'HSS F349 - ECOCRITICISM': 'ecocrit',
'GS F221 - BUSINESS COMMUNICATION': 'b comm',
'PHY F315 - THEORY OF RELATIVITY': 'TOR',
'PHY F215 - INTRO TO ASTRO & ASTROPH': 'astro',
}

cdf = df.copy()
short_sub = pd.Series(short_sub)
cdf['Short Sub'] = df['Subject'].map(short_sub)
cdf