# -*- coding: utf-8 -*-
"""emo slit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LotJPmMLk7YFTeJspyelufZaYI2LNx42
"""

data_path = "/content/drive/My Drive/bpgc acad/2-1/EMO lab/single and double slit/data.csv"

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

df = pd.read_csv(data_path, header = None)
df.columns = ['x','v','x','v', 'x','v', 'x','v']
df_single_A = df.iloc[:, 0:2].dropna()
df_single_B = df.iloc[:, 2:4].dropna()
df_double_A = df.iloc[:, 4:6]
df_double_B = df.iloc[:, 6:8]
df_double_A

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
dfs = [df_single_A, df_single_B, df_double_A, df_double_B]
for i in range(len(dfs)):
  d = dfs[i].copy()

  d = d.sort_values(by = 'x')
  d["I"] = d['v']**2
  d['delta v'] = d['v'].diff()
  d['delta I'] = d["I"].diff()

  dfs[i] = d.copy()
df_single_A, df_single_B, df_double_A, df_double_B = dfs

for d in (df_single_A,):
  fig = plt.figure(figsize = (5,5))
  ax = fig.add_subplot()
  ax.set_xticks(ticks = d['x'], minor = True)
  ax.plot(d['x'], d['I'])
  # ax.plot(d['x'], d['delta I'])
  xstart, xend = 9.5,15.5
  def I(x):
    return d[d['x']==x]['I']
  ax.plot((xstart, xstart), (-40, I(xstart)), color = 'gray', ls = '--', lw = 1)
  ax.plot((xend, xend), (-40, I(xend)), color = 'gray', ls = '--', lw = 1)
  ax.text(s = f'2x = {xstart}', x = (xstart+xend)/2, y = -10, horizontalalignment = 'center', verticalalignment = 'center', fontstyle = 'italic', fontsize = 12, fontname = 'serif')
  ax.arrow(x = xstart, y = -10, dx = 1, dy = 0)
  ax.arrow(x = xend, y = -10, dx = -1, dy = 0)
  ax.axhline(y = 0, lw = 0.5, color = 'gray', ls = '-')
  ax.set_xlabel('x (in mm)')
  ax.set_ylabel('Intensity --->')
  ax.spines['right'].set_visible(False)
  ax.set_yticks(ticks = [0])
  ax.spines['top'].set_visible(False)

  ax.set_ylim([-20,90])
  # ax.set_xlim([8,18])
  # print(d[(d['v']<0.2) & (d['v']>-0.2)])
  # print(d[d['x'].isin(list(np.arange(12,15,0.25)))])

df_double_B